language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
  - npm install
script:
  - npm run build
addons:
  ssh_known_hosts:
  - 139.224.236.71
before_install:
- openssl aes-256-cbc -K $encrypted_78c949b05bda_key -iv $encrypted_78c949b05bda_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_install:
  - chmod 600 ~/.ssh/id_rsa
  - ssh valtzweb@139.224.236.71 -o StrictHostKeyChecking=no 'cd ~/Valtzhao && git pull && npm install && npm run build' 
